# Generated by Django 3.1.2 on 2020-10-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='personal_workout',
        ),
    ]
