# Generated by Django 3.1.2 on 2020-10-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_profile_personal_workout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_add_workout', 'can_delete_workout'),)},
        ),
    ]
