# Generated by Django 3.1.2 on 2020-10-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_auto_20201025_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
    ]
