# Generated by Django 3.1.2 on 2020-10-29 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_remove_profile_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='start_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
