# Generated by Django 3.1.2 on 2020-10-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_workout_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='arm_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chest_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hip_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='waist',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
